import 'package:flutter/material.dart';

const SizedBox hSizedBox02 = SizedBox(width: 2);
const SizedBox hSizedBox05 = SizedBox(width: 5);
const SizedBox hSizedBox = SizedBox(width: 10);
const SizedBox hSizedBox15 = SizedBox(width: 15);
const SizedBox hSizedBox2 = SizedBox(width: 20);
const SizedBox hSizedBox3 = SizedBox(width: 30);
const SizedBox hSizedBox4 = SizedBox(width: 40);
const SizedBox hSizedBox6 = SizedBox(width: 60);
const SizedBox hSizedBox8 = SizedBox(width: 80);
const SizedBox vSizedBox02 = SizedBox(height: 2);
const SizedBox vSizedBox05 = SizedBox(height: 5);
const SizedBox vSizedBox = SizedBox(height: 10);
const SizedBox vSizedBox2 = SizedBox(height: 20);
const SizedBox vSizedBox3 = SizedBox(height: 30);
const SizedBox vSizedBox4 = SizedBox(height: 40);
const SizedBox vSizedBox6 = SizedBox(height: 60);
const SizedBox vSizedBox8 = SizedBox(height: 80);
const SizedBox vSizedBox100 = SizedBox(height: 100);
const SizedBox vSizedBox180 = SizedBox(height: 180);
const SizedBox vSizedBox200 = SizedBox(height: 200);
const SizedBox vSizedBox300 = SizedBox(height: 300);
